### ISSUE TITLE
[FR] - Update Wiki

### ISSUE THREAD

**Issue by Lorias-Jak** [Lorias-Jak/LoriTime#88]
## Currently missing
- [x] API

## Needs update
- [x] Update permissions
- [x] Config
- [x] Langfiles (Dont know if i have them in)
- [x] Custom configurable plugincommand alias
- [x] MultiSetup - When to use on proxy and subservers
- [x] Placeholder
- [x] Compatibility page - PlaceholderAPI integration
- [x] Remove Waterfall

## ToDo For the Future
- [x] Auto-Deploy Wiki on Push to Branch if Updated
  - [x] Bring Wiki to Repo Code
